
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("Dummy6.Resource", IsApplication=true)>]
    do ()

namespace TestAndroid
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnExceptionafd36a872dc44d3094e0da6b2ad0aaf7 of obj
    exception ReturnNoneExceptionafd36a872dc44d3094e0da6b2ad0aaf7
    [<AutoOpen>]
    module FuncConvertFinalOverloadafd36a872dc44d3094e0da6b2ad0aaf7 =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                ()


    
    and
        
        (* partial *)Resource_Animation () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040000
            static member abc_fade_in = 2130968576
            
            // aapt resource value: 0x7f040001
            static member abc_fade_out = 2130968577
            
            // aapt resource value: 0x7f040002
            static member abc_slide_in_bottom = 2130968578
            
            // aapt resource value: 0x7f040003
            static member abc_slide_in_top = 2130968579
            
            // aapt resource value: 0x7f040004
            static member abc_slide_out_bottom = 2130968580
            
            // aapt resource value: 0x7f040005
            static member abc_slide_out_top = 2130968581
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f01001c
            static member actionBarDivider = 2130771996
            
            // aapt resource value: 0x7f01001d
            static member actionBarItemBackground = 2130771997
            
            // aapt resource value: 0x7f01001b
            static member actionBarSize = 2130771995
            
            // aapt resource value: 0x7f010019
            static member actionBarSplitStyle = 2130771993
            
            // aapt resource value: 0x7f010018
            static member actionBarStyle = 2130771992
            
            // aapt resource value: 0x7f010015
            static member actionBarTabBarStyle = 2130771989
            
            // aapt resource value: 0x7f010014
            static member actionBarTabStyle = 2130771988
            
            // aapt resource value: 0x7f010016
            static member actionBarTabTextStyle = 2130771990
            
            // aapt resource value: 0x7f01001a
            static member actionBarWidgetTheme = 2130771994
            
            // aapt resource value: 0x7f010023
            static member actionButtonStyle = 2130772003
            
            // aapt resource value: 0x7f010054
            static member actionDropDownStyle = 2130772052
            
            // aapt resource value: 0x7f01005b
            static member actionLayout = 2130772059
            
            // aapt resource value: 0x7f01001e
            static member actionMenuTextAppearance = 2130771998
            
            // aapt resource value: 0x7f01001f
            static member actionMenuTextColor = 2130771999
            
            // aapt resource value: 0x7f010049
            static member actionModeBackground = 2130772041
            
            // aapt resource value: 0x7f010048
            static member actionModeCloseButtonStyle = 2130772040
            
            // aapt resource value: 0x7f01004b
            static member actionModeCloseDrawable = 2130772043
            
            // aapt resource value: 0x7f01004d
            static member actionModeCopyDrawable = 2130772045
            
            // aapt resource value: 0x7f01004c
            static member actionModeCutDrawable = 2130772044
            
            // aapt resource value: 0x7f010051
            static member actionModeFindDrawable = 2130772049
            
            // aapt resource value: 0x7f01004e
            static member actionModePasteDrawable = 2130772046
            
            // aapt resource value: 0x7f010053
            static member actionModePopupWindowStyle = 2130772051
            
            // aapt resource value: 0x7f01004f
            static member actionModeSelectAllDrawable = 2130772047
            
            // aapt resource value: 0x7f010050
            static member actionModeShareDrawable = 2130772048
            
            // aapt resource value: 0x7f01004a
            static member actionModeSplitBackground = 2130772042
            
            // aapt resource value: 0x7f010047
            static member actionModeStyle = 2130772039
            
            // aapt resource value: 0x7f010052
            static member actionModeWebSearchDrawable = 2130772050
            
            // aapt resource value: 0x7f010017
            static member actionOverflowButtonStyle = 2130771991
            
            // aapt resource value: 0x7f01005d
            static member actionProviderClass = 2130772061
            
            // aapt resource value: 0x7f01005c
            static member actionViewClass = 2130772060
            
            // aapt resource value: 0x7f010079
            static member activityChooserViewStyle = 2130772089
            
            // aapt resource value: 0x7f010000
            static member adSize = 2130771968
            
            // aapt resource value: 0x7f010001
            static member adSizes = 2130771969
            
            // aapt resource value: 0x7f010002
            static member adUnitId = 2130771970
            
            // aapt resource value: 0x7f01003c
            static member background = 2130772028
            
            // aapt resource value: 0x7f01003e
            static member backgroundSplit = 2130772030
            
            // aapt resource value: 0x7f01003d
            static member backgroundStacked = 2130772029
            
            // aapt resource value: 0x7f010025
            static member buttonBarButtonStyle = 2130772005
            
            // aapt resource value: 0x7f010024
            static member buttonBarStyle = 2130772004
            
            // aapt resource value: 0x7f010004
            static member cameraBearing = 2130771972
            
            // aapt resource value: 0x7f010005
            static member cameraTargetLat = 2130771973
            
            // aapt resource value: 0x7f010006
            static member cameraTargetLng = 2130771974
            
            // aapt resource value: 0x7f010007
            static member cameraTilt = 2130771975
            
            // aapt resource value: 0x7f010008
            static member cameraZoom = 2130771976
            
            // aapt resource value: 0x7f01003f
            static member customNavigationLayout = 2130772031
            
            // aapt resource value: 0x7f010061
            static member disableChildrenWhenDisabled = 2130772065
            
            // aapt resource value: 0x7f010035
            static member displayOptions = 2130772021
            
            // aapt resource value: 0x7f01003b
            static member divider = 2130772027
            
            // aapt resource value: 0x7f010028
            static member dividerHorizontal = 2130772008
            
            // aapt resource value: 0x7f010063
            static member dividerPadding = 2130772067
            
            // aapt resource value: 0x7f010027
            static member dividerVertical = 2130772007
            
            // aapt resource value: 0x7f01002e
            static member dropDownListViewStyle = 2130772014
            
            // aapt resource value: 0x7f010055
            static member dropdownListPreferredItemHeight = 2130772053
            
            // aapt resource value: 0x7f010078
            static member expandActivityOverflowButtonDrawable = 2130772088
            
            // aapt resource value: 0x7f01007b
            static member externalRouteEnabledDrawable = 2130772091
            
            // aapt resource value: 0x7f010033
            static member height = 2130772019
            
            // aapt resource value: 0x7f010020
            static member homeAsUpIndicator = 2130772000
            
            // aapt resource value: 0x7f010040
            static member homeLayout = 2130772032
            
            // aapt resource value: 0x7f010039
            static member icon = 2130772025
            
            // aapt resource value: 0x7f010067
            static member iconifiedByDefault = 2130772071
            
            // aapt resource value: 0x7f010042
            static member indeterminateProgressStyle = 2130772034
            
            // aapt resource value: 0x7f010077
            static member initialActivityCount = 2130772087
            
            // aapt resource value: 0x7f010066
            static member isLightTheme = 2130772070
            
            // aapt resource value: 0x7f010044
            static member itemPadding = 2130772036
            
            // aapt resource value: 0x7f010059
            static member listChoiceBackgroundIndicator = 2130772057
            
            // aapt resource value: 0x7f01002f
            static member listPopupWindowStyle = 2130772015
            
            // aapt resource value: 0x7f010029
            static member listPreferredItemHeight = 2130772009
            
            // aapt resource value: 0x7f01002b
            static member listPreferredItemHeightLarge = 2130772011
            
            // aapt resource value: 0x7f01002a
            static member listPreferredItemHeightSmall = 2130772010
            
            // aapt resource value: 0x7f01002c
            static member listPreferredItemPaddingLeft = 2130772012
            
            // aapt resource value: 0x7f01002d
            static member listPreferredItemPaddingRight = 2130772013
            
            // aapt resource value: 0x7f01003a
            static member logo = 2130772026
            
            // aapt resource value: 0x7f010003
            static member mapType = 2130771971
            
            // aapt resource value: 0x7f01007c
            static member mediaRouteButtonStyle = 2130772092
            
            // aapt resource value: 0x7f01007e
            static member mediaRouteConnectingDrawable = 2130772094
            
            // aapt resource value: 0x7f01007d
            static member mediaRouteOffDrawable = 2130772093
            
            // aapt resource value: 0x7f01007f
            static member mediaRouteOnDrawable = 2130772095
            
            // aapt resource value: 0x7f010034
            static member navigationMode = 2130772020
            
            // aapt resource value: 0x7f010046
            static member paddingEnd = 2130772038
            
            // aapt resource value: 0x7f010045
            static member paddingStart = 2130772037
            
            // aapt resource value: 0x7f010058
            static member panelMenuListTheme = 2130772056
            
            // aapt resource value: 0x7f010057
            static member panelMenuListWidth = 2130772055
            
            // aapt resource value: 0x7f010056
            static member popupMenuStyle = 2130772054
            
            // aapt resource value: 0x7f010060
            static member popupPromptView = 2130772064
            
            // aapt resource value: 0x7f010043
            static member progressBarPadding = 2130772035
            
            // aapt resource value: 0x7f010041
            static member progressBarStyle = 2130772033
            
            // aapt resource value: 0x7f01005e
            static member prompt = 2130772062
            
            // aapt resource value: 0x7f010068
            static member queryHint = 2130772072
            
            // aapt resource value: 0x7f010069
            static member searchDropdownBackground = 2130772073
            
            // aapt resource value: 0x7f010072
            static member searchResultListItemHeight = 2130772082
            
            // aapt resource value: 0x7f010076
            static member searchViewAutoCompleteTextView = 2130772086
            
            // aapt resource value: 0x7f01006a
            static member searchViewCloseIcon = 2130772074
            
            // aapt resource value: 0x7f01006e
            static member searchViewEditQuery = 2130772078
            
            // aapt resource value: 0x7f01006f
            static member searchViewEditQueryBackground = 2130772079
            
            // aapt resource value: 0x7f01006b
            static member searchViewGoIcon = 2130772075
            
            // aapt resource value: 0x7f01006c
            static member searchViewSearchIcon = 2130772076
            
            // aapt resource value: 0x7f010070
            static member searchViewTextField = 2130772080
            
            // aapt resource value: 0x7f010071
            static member searchViewTextFieldRight = 2130772081
            
            // aapt resource value: 0x7f01006d
            static member searchViewVoiceIcon = 2130772077
            
            // aapt resource value: 0x7f010026
            static member selectableItemBackground = 2130772006
            
            // aapt resource value: 0x7f01005a
            static member showAsAction = 2130772058
            
            // aapt resource value: 0x7f010062
            static member showDividers = 2130772066
            
            // aapt resource value: 0x7f010065
            static member spinnerDropDownItemStyle = 2130772069
            
            // aapt resource value: 0x7f01005f
            static member spinnerMode = 2130772063
            
            // aapt resource value: 0x7f010064
            static member spinnerStyle = 2130772068
            
            // aapt resource value: 0x7f010036
            static member subtitle = 2130772022
            
            // aapt resource value: 0x7f010038
            static member subtitleTextStyle = 2130772024
            
            // aapt resource value: 0x7f01007a
            static member textAllCaps = 2130772090
            
            // aapt resource value: 0x7f010021
            static member textAppearanceLargePopupMenu = 2130772001
            
            // aapt resource value: 0x7f010030
            static member textAppearanceListItem = 2130772016
            
            // aapt resource value: 0x7f010031
            static member textAppearanceListItemSmall = 2130772017
            
            // aapt resource value: 0x7f010074
            static member textAppearanceSearchResultSubtitle = 2130772084
            
            // aapt resource value: 0x7f010073
            static member textAppearanceSearchResultTitle = 2130772083
            
            // aapt resource value: 0x7f010022
            static member textAppearanceSmallPopupMenu = 2130772002
            
            // aapt resource value: 0x7f010075
            static member textColorSearchUrl = 2130772085
            
            // aapt resource value: 0x7f010032
            static member title = 2130772018
            
            // aapt resource value: 0x7f010037
            static member titleTextStyle = 2130772023
            
            // aapt resource value: 0x7f010009
            static member uiCompass = 2130771977
            
            // aapt resource value: 0x7f01000a
            static member uiRotateGestures = 2130771978
            
            // aapt resource value: 0x7f01000b
            static member uiScrollGestures = 2130771979
            
            // aapt resource value: 0x7f01000c
            static member uiTiltGestures = 2130771980
            
            // aapt resource value: 0x7f01000d
            static member uiZoomControls = 2130771981
            
            // aapt resource value: 0x7f01000e
            static member uiZoomGestures = 2130771982
            
            // aapt resource value: 0x7f01000f
            static member useViewLifecycle = 2130771983
            
            // aapt resource value: 0x7f010011
            static member windowActionBar = 2130771985
            
            // aapt resource value: 0x7f010012
            static member windowActionBarOverlay = 2130771986
            
            // aapt resource value: 0x7f010013
            static member windowSplitActionBar = 2130771987
            
            // aapt resource value: 0x7f010010
            static member zOrderOnTop = 2130771984
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Boolean () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f090000
            static member abc_action_bar_embed_tabs_pre_jb = 2131296256
            
            // aapt resource value: 0x7f090001
            static member abc_action_bar_expanded_action_views_exclusive = 2131296257
            
            // aapt resource value: 0x7f090005
            static member abc_config_actionMenuItemAllCaps = 2131296261
            
            // aapt resource value: 0x7f090004
            static member abc_config_allowActionMenuItemTextWithIcon = 2131296260
            
            // aapt resource value: 0x7f090003
            static member abc_config_showMenuShortcutsWhenKeyboardPresent = 2131296259
            
            // aapt resource value: 0x7f090002
            static member abc_split_action_bar_is_narrow = 2131296258
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Color () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f05000d
            static member abc_search_url_text_holo = 2131034125
            
            // aapt resource value: 0x7f05000a
            static member abc_search_url_text_normal = 2131034122
            
            // aapt resource value: 0x7f05000c
            static member abc_search_url_text_pressed = 2131034124
            
            // aapt resource value: 0x7f05000b
            static member abc_search_url_text_selected = 2131034123
            
            // aapt resource value: 0x7f050009
            static member common_action_bar_splitter = 2131034121
            
            // aapt resource value: 0x7f050000
            static member common_signin_btn_dark_text_default = 2131034112
            
            // aapt resource value: 0x7f050002
            static member common_signin_btn_dark_text_disabled = 2131034114
            
            // aapt resource value: 0x7f050003
            static member common_signin_btn_dark_text_focused = 2131034115
            
            // aapt resource value: 0x7f050001
            static member common_signin_btn_dark_text_pressed = 2131034113
            
            // aapt resource value: 0x7f050008
            static member common_signin_btn_default_background = 2131034120
            
            // aapt resource value: 0x7f050004
            static member common_signin_btn_light_text_default = 2131034116
            
            // aapt resource value: 0x7f050006
            static member common_signin_btn_light_text_disabled = 2131034118
            
            // aapt resource value: 0x7f050007
            static member common_signin_btn_light_text_focused = 2131034119
            
            // aapt resource value: 0x7f050005
            static member common_signin_btn_light_text_pressed = 2131034117
            
            // aapt resource value: 0x7f05000e
            static member common_signin_btn_text_dark = 2131034126
            
            // aapt resource value: 0x7f05000f
            static member common_signin_btn_text_light = 2131034127
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Dimension () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f0a0002
            static member abc_action_bar_default_height = 2131361794
            
            // aapt resource value: 0x7f0a0003
            static member abc_action_bar_icon_vertical_padding = 2131361795
            
            // aapt resource value: 0x7f0a000a
            static member abc_action_bar_progress_bar_size = 2131361802
            
            // aapt resource value: 0x7f0a0009
            static member abc_action_bar_stacked_max_height = 2131361801
            
            // aapt resource value: 0x7f0a0001
            static member abc_action_bar_stacked_tab_max_width = 2131361793
            
            // aapt resource value: 0x7f0a0007
            static member abc_action_bar_subtitle_bottom_margin = 2131361799
            
            // aapt resource value: 0x7f0a0005
            static member abc_action_bar_subtitle_text_size = 2131361797
            
            // aapt resource value: 0x7f0a0006
            static member abc_action_bar_subtitle_top_margin = 2131361798
            
            // aapt resource value: 0x7f0a0004
            static member abc_action_bar_title_text_size = 2131361796
            
            // aapt resource value: 0x7f0a0008
            static member abc_action_button_min_width = 2131361800
            
            // aapt resource value: 0x7f0a0000
            static member abc_config_prefDialogWidth = 2131361792
            
            // aapt resource value: 0x7f0a0010
            static member abc_dropdownitem_icon_width = 2131361808
            
            // aapt resource value: 0x7f0a000e
            static member abc_dropdownitem_text_padding_left = 2131361806
            
            // aapt resource value: 0x7f0a000f
            static member abc_dropdownitem_text_padding_right = 2131361807
            
            // aapt resource value: 0x7f0a000b
            static member abc_panel_menu_list_width = 2131361803
            
            // aapt resource value: 0x7f0a000d
            static member abc_search_view_preferred_width = 2131361805
            
            // aapt resource value: 0x7f0a000c
            static member abc_search_view_text_min_width = 2131361804
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member abc_ab_bottom_solid_dark_holo = 2130837504
            
            // aapt resource value: 0x7f020001
            static member abc_ab_bottom_solid_light_holo = 2130837505
            
            // aapt resource value: 0x7f020002
            static member abc_ab_bottom_transparent_dark_holo = 2130837506
            
            // aapt resource value: 0x7f020003
            static member abc_ab_bottom_transparent_light_holo = 2130837507
            
            // aapt resource value: 0x7f020004
            static member abc_ab_share_pack_holo_dark = 2130837508
            
            // aapt resource value: 0x7f020005
            static member abc_ab_share_pack_holo_light = 2130837509
            
            // aapt resource value: 0x7f020006
            static member abc_ab_solid_dark_holo = 2130837510
            
            // aapt resource value: 0x7f020007
            static member abc_ab_solid_light_holo = 2130837511
            
            // aapt resource value: 0x7f020008
            static member abc_ab_stacked_solid_dark_holo = 2130837512
            
            // aapt resource value: 0x7f020009
            static member abc_ab_stacked_solid_light_holo = 2130837513
            
            // aapt resource value: 0x7f02000a
            static member abc_ab_stacked_transparent_dark_holo = 2130837514
            
            // aapt resource value: 0x7f02000b
            static member abc_ab_stacked_transparent_light_holo = 2130837515
            
            // aapt resource value: 0x7f02000c
            static member abc_ab_transparent_dark_holo = 2130837516
            
            // aapt resource value: 0x7f02000d
            static member abc_ab_transparent_light_holo = 2130837517
            
            // aapt resource value: 0x7f02000e
            static member abc_cab_background_bottom_holo_dark = 2130837518
            
            // aapt resource value: 0x7f02000f
            static member abc_cab_background_bottom_holo_light = 2130837519
            
            // aapt resource value: 0x7f020010
            static member abc_cab_background_top_holo_dark = 2130837520
            
            // aapt resource value: 0x7f020011
            static member abc_cab_background_top_holo_light = 2130837521
            
            // aapt resource value: 0x7f020012
            static member abc_ic_ab_back_holo_dark = 2130837522
            
            // aapt resource value: 0x7f020013
            static member abc_ic_ab_back_holo_light = 2130837523
            
            // aapt resource value: 0x7f020014
            static member abc_ic_cab_done_holo_dark = 2130837524
            
            // aapt resource value: 0x7f020015
            static member abc_ic_cab_done_holo_light = 2130837525
            
            // aapt resource value: 0x7f020016
            static member abc_ic_clear = 2130837526
            
            // aapt resource value: 0x7f020017
            static member abc_ic_clear_disabled = 2130837527
            
            // aapt resource value: 0x7f020018
            static member abc_ic_clear_holo_light = 2130837528
            
            // aapt resource value: 0x7f020019
            static member abc_ic_clear_normal = 2130837529
            
            // aapt resource value: 0x7f02001a
            static member abc_ic_clear_search_api_disabled_holo_light = 2130837530
            
            // aapt resource value: 0x7f02001b
            static member abc_ic_clear_search_api_holo_light = 2130837531
            
            // aapt resource value: 0x7f02001c
            static member abc_ic_commit_search_api_holo_dark = 2130837532
            
            // aapt resource value: 0x7f02001d
            static member abc_ic_commit_search_api_holo_light = 2130837533
            
            // aapt resource value: 0x7f02001e
            static member abc_ic_go = 2130837534
            
            // aapt resource value: 0x7f02001f
            static member abc_ic_go_search_api_holo_light = 2130837535
            
            // aapt resource value: 0x7f020020
            static member abc_ic_menu_moreoverflow_normal_holo_dark = 2130837536
            
            // aapt resource value: 0x7f020021
            static member abc_ic_menu_moreoverflow_normal_holo_light = 2130837537
            
            // aapt resource value: 0x7f020022
            static member abc_ic_menu_share_holo_dark = 2130837538
            
            // aapt resource value: 0x7f020023
            static member abc_ic_menu_share_holo_light = 2130837539
            
            // aapt resource value: 0x7f020024
            static member abc_ic_search = 2130837540
            
            // aapt resource value: 0x7f020025
            static member abc_ic_search_api_holo_light = 2130837541
            
            // aapt resource value: 0x7f020026
            static member abc_ic_voice_search = 2130837542
            
            // aapt resource value: 0x7f020027
            static member abc_ic_voice_search_api_holo_light = 2130837543
            
            // aapt resource value: 0x7f020028
            static member abc_item_background_holo_dark = 2130837544
            
            // aapt resource value: 0x7f020029
            static member abc_item_background_holo_light = 2130837545
            
            // aapt resource value: 0x7f02002a
            static member abc_list_divider_holo_dark = 2130837546
            
            // aapt resource value: 0x7f02002b
            static member abc_list_divider_holo_light = 2130837547
            
            // aapt resource value: 0x7f02002c
            static member abc_list_focused_holo = 2130837548
            
            // aapt resource value: 0x7f02002d
            static member abc_list_longpressed_holo = 2130837549
            
            // aapt resource value: 0x7f02002e
            static member abc_list_pressed_holo_dark = 2130837550
            
            // aapt resource value: 0x7f02002f
            static member abc_list_pressed_holo_light = 2130837551
            
            // aapt resource value: 0x7f020030
            static member abc_list_selector_background_transition_holo_dark = 2130837552
            
            // aapt resource value: 0x7f020031
            static member abc_list_selector_background_transition_holo_light = 2130837553
            
            // aapt resource value: 0x7f020032
            static member abc_list_selector_disabled_holo_dark = 2130837554
            
            // aapt resource value: 0x7f020033
            static member abc_list_selector_disabled_holo_light = 2130837555
            
            // aapt resource value: 0x7f020034
            static member abc_list_selector_holo_dark = 2130837556
            
            // aapt resource value: 0x7f020035
            static member abc_list_selector_holo_light = 2130837557
            
            // aapt resource value: 0x7f020036
            static member abc_menu_dropdown_panel_holo_dark = 2130837558
            
            // aapt resource value: 0x7f020037
            static member abc_menu_dropdown_panel_holo_light = 2130837559
            
            // aapt resource value: 0x7f020038
            static member abc_menu_hardkey_panel_holo_dark = 2130837560
            
            // aapt resource value: 0x7f020039
            static member abc_menu_hardkey_panel_holo_light = 2130837561
            
            // aapt resource value: 0x7f02003a
            static member abc_search_dropdown_dark = 2130837562
            
            // aapt resource value: 0x7f02003b
            static member abc_search_dropdown_light = 2130837563
            
            // aapt resource value: 0x7f02003c
            static member abc_spinner_ab_default_holo_dark = 2130837564
            
            // aapt resource value: 0x7f02003d
            static member abc_spinner_ab_default_holo_light = 2130837565
            
            // aapt resource value: 0x7f02003e
            static member abc_spinner_ab_disabled_holo_dark = 2130837566
            
            // aapt resource value: 0x7f02003f
            static member abc_spinner_ab_disabled_holo_light = 2130837567
            
            // aapt resource value: 0x7f020040
            static member abc_spinner_ab_focused_holo_dark = 2130837568
            
            // aapt resource value: 0x7f020041
            static member abc_spinner_ab_focused_holo_light = 2130837569
            
            // aapt resource value: 0x7f020042
            static member abc_spinner_ab_holo_dark = 2130837570
            
            // aapt resource value: 0x7f020043
            static member abc_spinner_ab_holo_light = 2130837571
            
            // aapt resource value: 0x7f020044
            static member abc_spinner_ab_pressed_holo_dark = 2130837572
            
            // aapt resource value: 0x7f020045
            static member abc_spinner_ab_pressed_holo_light = 2130837573
            
            // aapt resource value: 0x7f020046
            static member abc_tab_indicator_ab_holo = 2130837574
            
            // aapt resource value: 0x7f020047
            static member abc_tab_selected_focused_holo = 2130837575
            
            // aapt resource value: 0x7f020048
            static member abc_tab_selected_holo = 2130837576
            
            // aapt resource value: 0x7f020049
            static member abc_tab_selected_pressed_holo = 2130837577
            
            // aapt resource value: 0x7f02004a
            static member abc_tab_unselected_pressed_holo = 2130837578
            
            // aapt resource value: 0x7f02004b
            static member abc_textfield_search_default_holo_dark = 2130837579
            
            // aapt resource value: 0x7f02004c
            static member abc_textfield_search_default_holo_light = 2130837580
            
            // aapt resource value: 0x7f02004d
            static member abc_textfield_search_right_default_holo_dark = 2130837581
            
            // aapt resource value: 0x7f02004e
            static member abc_textfield_search_right_default_holo_light = 2130837582
            
            // aapt resource value: 0x7f02004f
            static member abc_textfield_search_right_selected_holo_dark = 2130837583
            
            // aapt resource value: 0x7f020050
            static member abc_textfield_search_right_selected_holo_light = 2130837584
            
            // aapt resource value: 0x7f020051
            static member abc_textfield_search_selected_holo_dark = 2130837585
            
            // aapt resource value: 0x7f020052
            static member abc_textfield_search_selected_holo_light = 2130837586
            
            // aapt resource value: 0x7f020053
            static member abc_textfield_searchview_holo_dark = 2130837587
            
            // aapt resource value: 0x7f020054
            static member abc_textfield_searchview_holo_light = 2130837588
            
            // aapt resource value: 0x7f020055
            static member abc_textfield_searchview_right_holo_dark = 2130837589
            
            // aapt resource value: 0x7f020056
            static member abc_textfield_searchview_right_holo_light = 2130837590
            
            // aapt resource value: 0x7f020057
            static member common_signin_btn_icon_dark = 2130837591
            
            // aapt resource value: 0x7f020058
            static member common_signin_btn_icon_disabled_dark = 2130837592
            
            // aapt resource value: 0x7f020059
            static member common_signin_btn_icon_disabled_focus_dark = 2130837593
            
            // aapt resource value: 0x7f02005a
            static member common_signin_btn_icon_disabled_focus_light = 2130837594
            
            // aapt resource value: 0x7f02005b
            static member common_signin_btn_icon_disabled_light = 2130837595
            
            // aapt resource value: 0x7f02005c
            static member common_signin_btn_icon_focus_dark = 2130837596
            
            // aapt resource value: 0x7f02005d
            static member common_signin_btn_icon_focus_light = 2130837597
            
            // aapt resource value: 0x7f02005e
            static member common_signin_btn_icon_light = 2130837598
            
            // aapt resource value: 0x7f02005f
            static member common_signin_btn_icon_normal_dark = 2130837599
            
            // aapt resource value: 0x7f020060
            static member common_signin_btn_icon_normal_light = 2130837600
            
            // aapt resource value: 0x7f020061
            static member common_signin_btn_icon_pressed_dark = 2130837601
            
            // aapt resource value: 0x7f020062
            static member common_signin_btn_icon_pressed_light = 2130837602
            
            // aapt resource value: 0x7f020063
            static member common_signin_btn_text_dark = 2130837603
            
            // aapt resource value: 0x7f020064
            static member common_signin_btn_text_disabled_dark = 2130837604
            
            // aapt resource value: 0x7f020065
            static member common_signin_btn_text_disabled_focus_dark = 2130837605
            
            // aapt resource value: 0x7f020066
            static member common_signin_btn_text_disabled_focus_light = 2130837606
            
            // aapt resource value: 0x7f020067
            static member common_signin_btn_text_disabled_light = 2130837607
            
            // aapt resource value: 0x7f020068
            static member common_signin_btn_text_focus_dark = 2130837608
            
            // aapt resource value: 0x7f020069
            static member common_signin_btn_text_focus_light = 2130837609
            
            // aapt resource value: 0x7f02006a
            static member common_signin_btn_text_light = 2130837610
            
            // aapt resource value: 0x7f02006b
            static member common_signin_btn_text_normal_dark = 2130837611
            
            // aapt resource value: 0x7f02006c
            static member common_signin_btn_text_normal_light = 2130837612
            
            // aapt resource value: 0x7f02006d
            static member common_signin_btn_text_pressed_dark = 2130837613
            
            // aapt resource value: 0x7f02006e
            static member common_signin_btn_text_pressed_light = 2130837614
            
            // aapt resource value: 0x7f02006f
            static member ic_plusone_medium_off_client = 2130837615
            
            // aapt resource value: 0x7f020070
            static member ic_plusone_small_off_client = 2130837616
            
            // aapt resource value: 0x7f020071
            static member ic_plusone_standard_off_client = 2130837617
            
            // aapt resource value: 0x7f020072
            static member ic_plusone_tall_off_client = 2130837618
            
            // aapt resource value: 0x7f020073
            static member Icon = 2130837619
            
            // aapt resource value: 0x7f020074
            static member mr_ic_audio_vol = 2130837620
            
            // aapt resource value: 0x7f020075
            static member mr_ic_media_route_connecting_holo_dark = 2130837621
            
            // aapt resource value: 0x7f020076
            static member mr_ic_media_route_connecting_holo_light = 2130837622
            
            // aapt resource value: 0x7f020077
            static member mr_ic_media_route_disabled_holo_dark = 2130837623
            
            // aapt resource value: 0x7f020078
            static member mr_ic_media_route_disabled_holo_light = 2130837624
            
            // aapt resource value: 0x7f020079
            static member mr_ic_media_route_holo_dark = 2130837625
            
            // aapt resource value: 0x7f02007a
            static member mr_ic_media_route_holo_light = 2130837626
            
            // aapt resource value: 0x7f02007b
            static member mr_ic_media_route_off_holo_dark = 2130837627
            
            // aapt resource value: 0x7f02007c
            static member mr_ic_media_route_off_holo_light = 2130837628
            
            // aapt resource value: 0x7f02007d
            static member mr_ic_media_route_on_0_holo_dark = 2130837629
            
            // aapt resource value: 0x7f02007e
            static member mr_ic_media_route_on_0_holo_light = 2130837630
            
            // aapt resource value: 0x7f02007f
            static member mr_ic_media_route_on_1_holo_dark = 2130837631
            
            // aapt resource value: 0x7f020080
            static member mr_ic_media_route_on_1_holo_light = 2130837632
            
            // aapt resource value: 0x7f020081
            static member mr_ic_media_route_on_2_holo_dark = 2130837633
            
            // aapt resource value: 0x7f020082
            static member mr_ic_media_route_on_2_holo_light = 2130837634
            
            // aapt resource value: 0x7f020083
            static member mr_ic_media_route_on_holo_dark = 2130837635
            
            // aapt resource value: 0x7f020084
            static member mr_ic_media_route_on_holo_light = 2130837636
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f06001f
            static member action_bar = 2131099679
            
            // aapt resource value: 0x7f060018
            static member action_bar_activity_content = 2131099672
            
            // aapt resource value: 0x7f06001e
            static member action_bar_container = 2131099678
            
            // aapt resource value: 0x7f060022
            static member action_bar_overlay_layout = 2131099682
            
            // aapt resource value: 0x7f06001d
            static member action_bar_root = 2131099677
            
            // aapt resource value: 0x7f060026
            static member action_bar_subtitle = 2131099686
            
            // aapt resource value: 0x7f060025
            static member action_bar_title = 2131099685
            
            // aapt resource value: 0x7f060020
            static member action_context_bar = 2131099680
            
            // aapt resource value: 0x7f060019
            static member action_menu_divider = 2131099673
            
            // aapt resource value: 0x7f06001a
            static member action_menu_presenter = 2131099674
            
            // aapt resource value: 0x7f060027
            static member action_mode_close_button = 2131099687
            
            // aapt resource value: 0x7f060028
            static member activity_chooser_view_content = 2131099688
            
            // aapt resource value: 0x7f06000f
            static member always = 2131099663
            
            // aapt resource value: 0x7f060014
            static member beginning = 2131099668
            
            // aapt resource value: 0x7f060030
            static member checkbox = 2131099696
            
            // aapt resource value: 0x7f060011
            static member collapseActionView = 2131099665
            
            // aapt resource value: 0x7f06002b
            static member default_activity_button = 2131099691
            
            // aapt resource value: 0x7f060012
            static member dialog = 2131099666
            
            // aapt resource value: 0x7f06000c
            static member disableHome = 2131099660
            
            // aapt resource value: 0x7f060013
            static member dropdown = 2131099667
            
            // aapt resource value: 0x7f060033
            static member edit_query = 2131099699
            
            // aapt resource value: 0x7f060016
            //how do we stop Droid form renegerating this, which has a tag with an illegal keyword, "end"??
            //static member end = 2131099670
            
            // aapt resource value: 0x7f060029
            static member expand_activities_button = 2131099689
            
            // aapt resource value: 0x7f06002f
            static member expanded_menu = 2131099695
            
            // aapt resource value: 0x7f060017
            static member home = 2131099671
            
            // aapt resource value: 0x7f060009
            static member homeAsUp = 2131099657
            
            // aapt resource value: 0x7f060004
            static member hybrid = 2131099652
            
            // aapt resource value: 0x7f06002d
            static member icon = 2131099693
            
            // aapt resource value: 0x7f06000e
            static member ifRoom = 2131099662
            
            // aapt resource value: 0x7f06002a
            static member image = 2131099690
            
            // aapt resource value: 0x7f060005
            static member listMode = 2131099653
            
            // aapt resource value: 0x7f06002c
            static member list_item = 2131099692
            
            // aapt resource value: 0x7f060043
            static member media_route_control_frame = 2131099715
            
            // aapt resource value: 0x7f060044
            static member media_route_disconnect_button = 2131099716
            
            // aapt resource value: 0x7f060040
            static member media_route_list = 2131099712
            
            // aapt resource value: 0x7f060041
            static member media_route_volume_layout = 2131099713
            
            // aapt resource value: 0x7f060042
            static member media_route_volume_slider = 2131099714
            
            // aapt resource value: 0x7f060015
            static member middle = 2131099669
            
            // aapt resource value: 0x7f06003f
            static member myButton = 2131099711
            
            // aapt resource value: 0x7f06000d
            static member never = 2131099661
            
            // aapt resource value: 0x7f060000
            static member none = 2131099648
            
            // aapt resource value: 0x7f060001
            static member normal = 2131099649
            
            // aapt resource value: 0x7f06001b
            static member progress_circular = 2131099675
            
            // aapt resource value: 0x7f06001c
            static member progress_horizontal = 2131099676
            
            // aapt resource value: 0x7f060032
            static member radio = 2131099698
            
            // aapt resource value: 0x7f060002
            static member satellite = 2131099650
            
            // aapt resource value: 0x7f060035
            static member search_badge = 2131099701
            
            // aapt resource value: 0x7f060034
            static member search_bar = 2131099700
            
            // aapt resource value: 0x7f060036
            static member search_button = 2131099702
            
            // aapt resource value: 0x7f06003b
            static member search_close_btn = 2131099707
            
            // aapt resource value: 0x7f060037
            static member search_edit_frame = 2131099703
            
            // aapt resource value: 0x7f06003d
            static member search_go_btn = 2131099709
            
            // aapt resource value: 0x7f060038
            static member search_mag_icon = 2131099704
            
            // aapt resource value: 0x7f060039
            static member search_plate = 2131099705
            
            // aapt resource value: 0x7f06003a
            static member search_src_text = 2131099706
            
            // aapt resource value: 0x7f06003e
            static member search_voice_btn = 2131099710
            
            // aapt resource value: 0x7f060031
            static member shortcut = 2131099697
            
            // aapt resource value: 0x7f06000b
            static member showCustom = 2131099659
            
            // aapt resource value: 0x7f060008
            static member showHome = 2131099656
            
            // aapt resource value: 0x7f06000a
            static member showTitle = 2131099658
            
            // aapt resource value: 0x7f060021
            static member split_action_bar = 2131099681
            
            // aapt resource value: 0x7f06003c
            static member submit_area = 2131099708
            
            // aapt resource value: 0x7f060006
            static member tabMode = 2131099654
            
            // aapt resource value: 0x7f060003
            static member terrain = 2131099651
            
            // aapt resource value: 0x7f06002e
            static member title = 2131099694
            
            // aapt resource value: 0x7f060023
            static member top_action_bar = 2131099683
            
            // aapt resource value: 0x7f060024
            static member up = 2131099684
            
            // aapt resource value: 0x7f060007
            static member useLogo = 2131099655
            
            // aapt resource value: 0x7f060010
            static member withText = 2131099664
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Integer () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f080001
            static member abc_max_action_buttons = 2131230721
            
            // aapt resource value: 0x7f080000
            static member google_play_services_version = 2131230720
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member abc_action_bar_decor = 2130903040
            
            // aapt resource value: 0x7f030001
            static member abc_action_bar_decor_include = 2130903041
            
            // aapt resource value: 0x7f030002
            static member abc_action_bar_decor_overlay = 2130903042
            
            // aapt resource value: 0x7f030003
            static member abc_action_bar_home = 2130903043
            
            // aapt resource value: 0x7f030004
            static member abc_action_bar_tab = 2130903044
            
            // aapt resource value: 0x7f030005
            static member abc_action_bar_tabbar = 2130903045
            
            // aapt resource value: 0x7f030006
            static member abc_action_bar_title_item = 2130903046
            
            // aapt resource value: 0x7f030007
            static member abc_action_bar_view_list_nav_layout = 2130903047
            
            // aapt resource value: 0x7f030008
            static member abc_action_menu_item_layout = 2130903048
            
            // aapt resource value: 0x7f030009
            static member abc_action_menu_layout = 2130903049
            
            // aapt resource value: 0x7f03000a
            static member abc_action_mode_bar = 2130903050
            
            // aapt resource value: 0x7f03000b
            static member abc_action_mode_close_item = 2130903051
            
            // aapt resource value: 0x7f03000c
            static member abc_activity_chooser_view = 2130903052
            
            // aapt resource value: 0x7f03000d
            static member abc_activity_chooser_view_include = 2130903053
            
            // aapt resource value: 0x7f03000e
            static member abc_activity_chooser_view_list_item = 2130903054
            
            // aapt resource value: 0x7f03000f
            static member abc_expanded_menu_layout = 2130903055
            
            // aapt resource value: 0x7f030010
            static member abc_list_menu_item_checkbox = 2130903056
            
            // aapt resource value: 0x7f030011
            static member abc_list_menu_item_icon = 2130903057
            
            // aapt resource value: 0x7f030012
            static member abc_list_menu_item_layout = 2130903058
            
            // aapt resource value: 0x7f030013
            static member abc_list_menu_item_radio = 2130903059
            
            // aapt resource value: 0x7f030014
            static member abc_popup_menu_item_layout = 2130903060
            
            // aapt resource value: 0x7f030015
            static member abc_search_dropdown_item_icons_2line = 2130903061
            
            // aapt resource value: 0x7f030016
            static member abc_search_view = 2130903062
            
            // aapt resource value: 0x7f030017
            static member Main = 2130903063
            
            // aapt resource value: 0x7f030018
            static member mr_media_route_chooser_dialog = 2130903064
            
            // aapt resource value: 0x7f030019
            static member mr_media_route_controller_dialog = 2130903065
            
            // aapt resource value: 0x7f03001a
            static member mr_media_route_list_item = 2130903066
            
            // aapt resource value: 0x7f03001b
            static member support_simple_spinner_dropdown_item = 2130903067
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f07001b
            static member abc_action_bar_home_description = 2131165211
            
            // aapt resource value: 0x7f07001c
            static member abc_action_bar_up_description = 2131165212
            
            // aapt resource value: 0x7f07001d
            static member abc_action_menu_overflow_description = 2131165213
            
            // aapt resource value: 0x7f07001a
            static member abc_action_mode_done = 2131165210
            
            // aapt resource value: 0x7f070024
            static member abc_activity_chooser_view_see_all = 2131165220
            
            // aapt resource value: 0x7f070023
            static member abc_activitychooserview_choose_application = 2131165219
            
            // aapt resource value: 0x7f070020
            static member abc_searchview_description_clear = 2131165216
            
            // aapt resource value: 0x7f07001f
            static member abc_searchview_description_query = 2131165215
            
            // aapt resource value: 0x7f07001e
            static member abc_searchview_description_search = 2131165214
            
            // aapt resource value: 0x7f070021
            static member abc_searchview_description_submit = 2131165217
            
            // aapt resource value: 0x7f070022
            static member abc_searchview_description_voice = 2131165218
            
            // aapt resource value: 0x7f070026
            static member abc_shareactionprovider_share_with = 2131165222
            
            // aapt resource value: 0x7f070025
            static member abc_shareactionprovider_share_with_application = 2131165221
            
            // aapt resource value: 0x7f07002e
            static member app_name = 2131165230
            
            // aapt resource value: 0x7f070015
            static member auth_client_needs_enabling_title = 2131165205
            
            // aapt resource value: 0x7f070016
            static member auth_client_needs_installation_title = 2131165206
            
            // aapt resource value: 0x7f070017
            static member auth_client_needs_update_title = 2131165207
            
            // aapt resource value: 0x7f070018
            static member auth_client_play_services_err_notification_msg = 2131165208
            
            // aapt resource value: 0x7f070019
            static member auth_client_requested_by_msg = 2131165209
            
            // aapt resource value: 0x7f070014
            static member auth_client_using_bad_version_title = 2131165204
            
            // aapt resource value: 0x7f070006
            static member common_google_play_services_enable_button = 2131165190
            
            // aapt resource value: 0x7f070005
            static member common_google_play_services_enable_text = 2131165189
            
            // aapt resource value: 0x7f070004
            static member common_google_play_services_enable_title = 2131165188
            
            // aapt resource value: 0x7f070003
            static member common_google_play_services_install_button = 2131165187
            
            // aapt resource value: 0x7f070001
            static member common_google_play_services_install_text_phone = 2131165185
            
            // aapt resource value: 0x7f070002
            static member common_google_play_services_install_text_tablet = 2131165186
            
            // aapt resource value: 0x7f070000
            static member common_google_play_services_install_title = 2131165184
            
            // aapt resource value: 0x7f07000c
            static member common_google_play_services_invalid_account_text = 2131165196
            
            // aapt resource value: 0x7f07000b
            static member common_google_play_services_invalid_account_title = 2131165195
            
            // aapt resource value: 0x7f07000a
            static member common_google_play_services_network_error_text = 2131165194
            
            // aapt resource value: 0x7f070009
            static member common_google_play_services_network_error_title = 2131165193
            
            // aapt resource value: 0x7f07000d
            static member common_google_play_services_unknown_issue = 2131165197
            
            // aapt resource value: 0x7f070010
            static member common_google_play_services_unsupported_date_text = 2131165200
            
            // aapt resource value: 0x7f07000f
            static member common_google_play_services_unsupported_text = 2131165199
            
            // aapt resource value: 0x7f07000e
            static member common_google_play_services_unsupported_title = 2131165198
            
            // aapt resource value: 0x7f070011
            static member common_google_play_services_update_button = 2131165201
            
            // aapt resource value: 0x7f070008
            static member common_google_play_services_update_text = 2131165192
            
            // aapt resource value: 0x7f070007
            static member common_google_play_services_update_title = 2131165191
            
            // aapt resource value: 0x7f070012
            static member common_signin_button_text = 2131165202
            
            // aapt resource value: 0x7f070013
            static member common_signin_button_text_long = 2131165203
            
            // aapt resource value: 0x7f07002d
            static member hello = 2131165229
            
            // aapt resource value: 0x7f070029
            static member mr_media_route_button_content_description = 2131165225
            
            // aapt resource value: 0x7f07002b
            static member mr_media_route_chooser_searching = 2131165227
            
            // aapt resource value: 0x7f07002a
            static member mr_media_route_chooser_title = 2131165226
            
            // aapt resource value: 0x7f07002c
            static member mr_media_route_controller_disconnect = 2131165228
            
            // aapt resource value: 0x7f070027
            static member mr_system_route_name = 2131165223
            
            // aapt resource value: 0x7f070028
            static member mr_user_route_category_name = 2131165224
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Style () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f0b0063
            static member TextAppearance_AppCompat_Base_CompactMenu_Dialog = 2131427427
            
            // aapt resource value: 0x7f0b006d
            static member TextAppearance_AppCompat_Base_SearchResult = 2131427437
            
            // aapt resource value: 0x7f0b006f
            static member TextAppearance_AppCompat_Base_SearchResult_Subtitle = 2131427439
            
            // aapt resource value: 0x7f0b006e
            static member TextAppearance_AppCompat_Base_SearchResult_Title = 2131427438
            
            // aapt resource value: 0x7f0b0069
            static member TextAppearance_AppCompat_Base_Widget_PopupMenu_Large = 2131427433
            
            // aapt resource value: 0x7f0b006a
            static member TextAppearance_AppCompat_Base_Widget_PopupMenu_Small = 2131427434
            
            // aapt resource value: 0x7f0b0070
            static member TextAppearance_AppCompat_Light_Base_SearchResult = 2131427440
            
            // aapt resource value: 0x7f0b0072
            static member TextAppearance_AppCompat_Light_Base_SearchResult_Subtitle = 2131427442
            
            // aapt resource value: 0x7f0b0071
            static member TextAppearance_AppCompat_Light_Base_SearchResult_Title = 2131427441
            
            // aapt resource value: 0x7f0b006b
            static member TextAppearance_AppCompat_Light_Base_Widget_PopupMenu_Large = 2131427435
            
            // aapt resource value: 0x7f0b006c
            static member TextAppearance_AppCompat_Light_Base_Widget_PopupMenu_Small = 2131427436
            
            // aapt resource value: 0x7f0b0035
            static member TextAppearance_AppCompat_Light_SearchResult_Subtitle = 2131427381
            
            // aapt resource value: 0x7f0b0034
            static member TextAppearance_AppCompat_Light_SearchResult_Title = 2131427380
            
            // aapt resource value: 0x7f0b0030
            static member TextAppearance_AppCompat_Light_Widget_PopupMenu_Large = 2131427376
            
            // aapt resource value: 0x7f0b0031
            static member TextAppearance_AppCompat_Light_Widget_PopupMenu_Small = 2131427377
            
            // aapt resource value: 0x7f0b0033
            static member TextAppearance_AppCompat_SearchResult_Subtitle = 2131427379
            
            // aapt resource value: 0x7f0b0032
            static member TextAppearance_AppCompat_SearchResult_Title = 2131427378
            
            // aapt resource value: 0x7f0b001a
            static member TextAppearance_AppCompat_Widget_ActionBar_Menu = 2131427354
            
            // aapt resource value: 0x7f0b0006
            static member TextAppearance_AppCompat_Widget_ActionBar_Subtitle = 2131427334
            
            // aapt resource value: 0x7f0b0008
            static member TextAppearance_AppCompat_Widget_ActionBar_Subtitle_Inverse = 2131427336
            
            // aapt resource value: 0x7f0b0005
            static member TextAppearance_AppCompat_Widget_ActionBar_Title = 2131427333
            
            // aapt resource value: 0x7f0b0007
            static member TextAppearance_AppCompat_Widget_ActionBar_Title_Inverse = 2131427335
            
            // aapt resource value: 0x7f0b001e
            static member TextAppearance_AppCompat_Widget_ActionMode_Subtitle = 2131427358
            
            // aapt resource value: 0x7f0b0020
            static member TextAppearance_AppCompat_Widget_ActionMode_Subtitle_Inverse = 2131427360
            
            // aapt resource value: 0x7f0b001d
            static member TextAppearance_AppCompat_Widget_ActionMode_Title = 2131427357
            
            // aapt resource value: 0x7f0b001f
            static member TextAppearance_AppCompat_Widget_ActionMode_Title_Inverse = 2131427359
            
            // aapt resource value: 0x7f0b0054
            static member TextAppearance_AppCompat_Widget_Base_ActionBar_Menu = 2131427412
            
            // aapt resource value: 0x7f0b0056
            static member TextAppearance_AppCompat_Widget_Base_ActionBar_Subtitle = 2131427414
            
            // aapt resource value: 0x7f0b0058
            static member TextAppearance_AppCompat_Widget_Base_ActionBar_Subtitle_Inverse = 2131427416
            
            // aapt resource value: 0x7f0b0055
            static member TextAppearance_AppCompat_Widget_Base_ActionBar_Title = 2131427413
            
            // aapt resource value: 0x7f0b0057
            static member TextAppearance_AppCompat_Widget_Base_ActionBar_Title_Inverse = 2131427415
            
            // aapt resource value: 0x7f0b0051
            static member TextAppearance_AppCompat_Widget_Base_ActionMode_Subtitle = 2131427409
            
            // aapt resource value: 0x7f0b0053
            static member TextAppearance_AppCompat_Widget_Base_ActionMode_Subtitle_Inverse = 2131427411
            
            // aapt resource value: 0x7f0b0050
            static member TextAppearance_AppCompat_Widget_Base_ActionMode_Title = 2131427408
            
            // aapt resource value: 0x7f0b0052
            static member TextAppearance_AppCompat_Widget_Base_ActionMode_Title_Inverse = 2131427410
            
            // aapt resource value: 0x7f0b0061
            static member TextAppearance_AppCompat_Widget_Base_DropDownItem = 2131427425
            
            // aapt resource value: 0x7f0b0021
            static member TextAppearance_AppCompat_Widget_DropDownItem = 2131427361
            
            // aapt resource value: 0x7f0b002e
            static member TextAppearance_AppCompat_Widget_PopupMenu_Large = 2131427374
            
            // aapt resource value: 0x7f0b002f
            static member TextAppearance_AppCompat_Widget_PopupMenu_Small = 2131427375
            
            // aapt resource value: 0x7f0b0062
            static member TextAppearance_Widget_AppCompat_Base_ExpandedMenu_Item = 2131427426
            
            // aapt resource value: 0x7f0b0028
            static member TextAppearance_Widget_AppCompat_ExpandedMenu_Item = 2131427368
            
            // aapt resource value: 0x7f0b0077
            static member Theme_AppCompat = 2131427447
            
            // aapt resource value: 0x7f0b0081
            static member Theme_AppCompat_Base_CompactMenu = 2131427457
            
            // aapt resource value: 0x7f0b0082
            static member Theme_AppCompat_Base_CompactMenu_Dialog = 2131427458
            
            // aapt resource value: 0x7f0b007a
            static member Theme_AppCompat_CompactMenu = 2131427450
            
            // aapt resource value: 0x7f0b007b
            static member Theme_AppCompat_CompactMenu_Dialog = 2131427451
            
            // aapt resource value: 0x7f0b0078
            static member Theme_AppCompat_Light = 2131427448
            
            // aapt resource value: 0x7f0b0079
            static member Theme_AppCompat_Light_DarkActionBar = 2131427449
            
            // aapt resource value: 0x7f0b007c
            static member Theme_Base = 2131427452
            
            // aapt resource value: 0x7f0b007e
            static member Theme_Base_AppCompat = 2131427454
            
            // aapt resource value: 0x7f0b007f
            static member Theme_Base_AppCompat_Light = 2131427455
            
            // aapt resource value: 0x7f0b0080
            static member Theme_Base_AppCompat_Light_DarkActionBar = 2131427456
            
            // aapt resource value: 0x7f0b007d
            static member Theme_Base_Light = 2131427453
            
            // aapt resource value: 0x7f0b0085
            static member Theme_MediaRouter = 2131427461
            
            // aapt resource value: 0x7f0b0086
            static member Theme_MediaRouter_Light = 2131427462
            
            // aapt resource value: 0x7f0b0000
            static member Widget_AppCompat_ActionBar = 2131427328
            
            // aapt resource value: 0x7f0b0002
            static member Widget_AppCompat_ActionBar_Solid = 2131427330
            
            // aapt resource value: 0x7f0b0011
            static member Widget_AppCompat_ActionBar_TabBar = 2131427345
            
            // aapt resource value: 0x7f0b0017
            static member Widget_AppCompat_ActionBar_TabText = 2131427351
            
            // aapt resource value: 0x7f0b0014
            static member Widget_AppCompat_ActionBar_TabView = 2131427348
            
            // aapt resource value: 0x7f0b000b
            static member Widget_AppCompat_ActionButton = 2131427339
            
            // aapt resource value: 0x7f0b000d
            static member Widget_AppCompat_ActionButton_CloseMode = 2131427341
            
            // aapt resource value: 0x7f0b000f
            static member Widget_AppCompat_ActionButton_Overflow = 2131427343
            
            // aapt resource value: 0x7f0b001b
            static member Widget_AppCompat_ActionMode = 2131427355
            
            // aapt resource value: 0x7f0b0038
            static member Widget_AppCompat_ActivityChooserView = 2131427384
            
            // aapt resource value: 0x7f0b0036
            static member Widget_AppCompat_AutoCompleteTextView = 2131427382
            
            // aapt resource value: 0x7f0b003a
            static member Widget_AppCompat_Base_ActionBar = 2131427386
            
            // aapt resource value: 0x7f0b003c
            static member Widget_AppCompat_Base_ActionBar_Solid = 2131427388
            
            // aapt resource value: 0x7f0b0045
            static member Widget_AppCompat_Base_ActionBar_TabBar = 2131427397
            
            // aapt resource value: 0x7f0b004b
            static member Widget_AppCompat_Base_ActionBar_TabText = 2131427403
            
            // aapt resource value: 0x7f0b0048
            static member Widget_AppCompat_Base_ActionBar_TabView = 2131427400
            
            // aapt resource value: 0x7f0b003f
            static member Widget_AppCompat_Base_ActionButton = 2131427391
            
            // aapt resource value: 0x7f0b0041
            static member Widget_AppCompat_Base_ActionButton_CloseMode = 2131427393
            
            // aapt resource value: 0x7f0b0043
            static member Widget_AppCompat_Base_ActionButton_Overflow = 2131427395
            
            // aapt resource value: 0x7f0b004e
            static member Widget_AppCompat_Base_ActionMode = 2131427406
            
            // aapt resource value: 0x7f0b0075
            static member Widget_AppCompat_Base_ActivityChooserView = 2131427445
            
            // aapt resource value: 0x7f0b0073
            static member Widget_AppCompat_Base_AutoCompleteTextView = 2131427443
            
            // aapt resource value: 0x7f0b005d
            static member Widget_AppCompat_Base_DropDownItem_Spinner = 2131427421
            
            // aapt resource value: 0x7f0b0065
            static member Widget_AppCompat_Base_ListPopupWindow = 2131427429
            
            // aapt resource value: 0x7f0b005f
            static member Widget_AppCompat_Base_ListView_DropDown = 2131427423
            
            // aapt resource value: 0x7f0b0064
            static member Widget_AppCompat_Base_ListView_Menu = 2131427428
            
            // aapt resource value: 0x7f0b0067
            static member Widget_AppCompat_Base_PopupMenu = 2131427431
            
            // aapt resource value: 0x7f0b005a
            static member Widget_AppCompat_Base_ProgressBar = 2131427418
            
            // aapt resource value: 0x7f0b0059
            static member Widget_AppCompat_Base_ProgressBar_Horizontal = 2131427417
            
            // aapt resource value: 0x7f0b005b
            static member Widget_AppCompat_Base_Spinner = 2131427419
            
            // aapt resource value: 0x7f0b0024
            static member Widget_AppCompat_DropDownItem_Spinner = 2131427364
            
            // aapt resource value: 0x7f0b0001
            static member Widget_AppCompat_Light_ActionBar = 2131427329
            
            // aapt resource value: 0x7f0b0003
            static member Widget_AppCompat_Light_ActionBar_Solid = 2131427331
            
            // aapt resource value: 0x7f0b0004
            static member Widget_AppCompat_Light_ActionBar_Solid_Inverse = 2131427332
            
            // aapt resource value: 0x7f0b0012
            static member Widget_AppCompat_Light_ActionBar_TabBar = 2131427346
            
            // aapt resource value: 0x7f0b0013
            static member Widget_AppCompat_Light_ActionBar_TabBar_Inverse = 2131427347
            
            // aapt resource value: 0x7f0b0018
            static member Widget_AppCompat_Light_ActionBar_TabText = 2131427352
            
            // aapt resource value: 0x7f0b0019
            static member Widget_AppCompat_Light_ActionBar_TabText_Inverse = 2131427353
            
            // aapt resource value: 0x7f0b0015
            static member Widget_AppCompat_Light_ActionBar_TabView = 2131427349
            
            // aapt resource value: 0x7f0b0016
            static member Widget_AppCompat_Light_ActionBar_TabView_Inverse = 2131427350
            
            // aapt resource value: 0x7f0b000c
            static member Widget_AppCompat_Light_ActionButton = 2131427340
            
            // aapt resource value: 0x7f0b000e
            static member Widget_AppCompat_Light_ActionButton_CloseMode = 2131427342
            
            // aapt resource value: 0x7f0b0010
            static member Widget_AppCompat_Light_ActionButton_Overflow = 2131427344
            
            // aapt resource value: 0x7f0b001c
            static member Widget_AppCompat_Light_ActionMode_Inverse = 2131427356
            
            // aapt resource value: 0x7f0b0039
            static member Widget_AppCompat_Light_ActivityChooserView = 2131427385
            
            // aapt resource value: 0x7f0b0037
            static member Widget_AppCompat_Light_AutoCompleteTextView = 2131427383
            
            // aapt resource value: 0x7f0b003b
            static member Widget_AppCompat_Light_Base_ActionBar = 2131427387
            
            // aapt resource value: 0x7f0b003d
            static member Widget_AppCompat_Light_Base_ActionBar_Solid = 2131427389
            
            // aapt resource value: 0x7f0b003e
            static member Widget_AppCompat_Light_Base_ActionBar_Solid_Inverse = 2131427390
            
            // aapt resource value: 0x7f0b0046
            static member Widget_AppCompat_Light_Base_ActionBar_TabBar = 2131427398
            
            // aapt resource value: 0x7f0b0047
            static member Widget_AppCompat_Light_Base_ActionBar_TabBar_Inverse = 2131427399
            
            // aapt resource value: 0x7f0b004c
            static member Widget_AppCompat_Light_Base_ActionBar_TabText = 2131427404
            
            // aapt resource value: 0x7f0b004d
            static member Widget_AppCompat_Light_Base_ActionBar_TabText_Inverse = 2131427405
            
            // aapt resource value: 0x7f0b0049
            static member Widget_AppCompat_Light_Base_ActionBar_TabView = 2131427401
            
            // aapt resource value: 0x7f0b004a
            static member Widget_AppCompat_Light_Base_ActionBar_TabView_Inverse = 2131427402
            
            // aapt resource value: 0x7f0b0040
            static member Widget_AppCompat_Light_Base_ActionButton = 2131427392
            
            // aapt resource value: 0x7f0b0042
            static member Widget_AppCompat_Light_Base_ActionButton_CloseMode = 2131427394
            
            // aapt resource value: 0x7f0b0044
            static member Widget_AppCompat_Light_Base_ActionButton_Overflow = 2131427396
            
            // aapt resource value: 0x7f0b004f
            static member Widget_AppCompat_Light_Base_ActionMode_Inverse = 2131427407
            
            // aapt resource value: 0x7f0b0076
            static member Widget_AppCompat_Light_Base_ActivityChooserView = 2131427446
            
            // aapt resource value: 0x7f0b0074
            static member Widget_AppCompat_Light_Base_AutoCompleteTextView = 2131427444
            
            // aapt resource value: 0x7f0b005e
            static member Widget_AppCompat_Light_Base_DropDownItem_Spinner = 2131427422
            
            // aapt resource value: 0x7f0b0066
            static member Widget_AppCompat_Light_Base_ListPopupWindow = 2131427430
            
            // aapt resource value: 0x7f0b0060
            static member Widget_AppCompat_Light_Base_ListView_DropDown = 2131427424
            
            // aapt resource value: 0x7f0b0068
            static member Widget_AppCompat_Light_Base_PopupMenu = 2131427432
            
            // aapt resource value: 0x7f0b005c
            static member Widget_AppCompat_Light_Base_Spinner = 2131427420
            
            // aapt resource value: 0x7f0b0025
            static member Widget_AppCompat_Light_DropDownItem_Spinner = 2131427365
            
            // aapt resource value: 0x7f0b002a
            static member Widget_AppCompat_Light_ListPopupWindow = 2131427370
            
            // aapt resource value: 0x7f0b0027
            static member Widget_AppCompat_Light_ListView_DropDown = 2131427367
            
            // aapt resource value: 0x7f0b002c
            static member Widget_AppCompat_Light_PopupMenu = 2131427372
            
            // aapt resource value: 0x7f0b0023
            static member Widget_AppCompat_Light_Spinner_DropDown_ActionBar = 2131427363
            
            // aapt resource value: 0x7f0b0029
            static member Widget_AppCompat_ListPopupWindow = 2131427369
            
            // aapt resource value: 0x7f0b0026
            static member Widget_AppCompat_ListView_DropDown = 2131427366
            
            // aapt resource value: 0x7f0b002d
            static member Widget_AppCompat_ListView_Menu = 2131427373
            
            // aapt resource value: 0x7f0b002b
            static member Widget_AppCompat_PopupMenu = 2131427371
            
            // aapt resource value: 0x7f0b000a
            static member Widget_AppCompat_ProgressBar = 2131427338
            
            // aapt resource value: 0x7f0b0009
            static member Widget_AppCompat_ProgressBar_Horizontal = 2131427337
            
            // aapt resource value: 0x7f0b0022
            static member Widget_AppCompat_Spinner_DropDown_ActionBar = 2131427362
            
            // aapt resource value: 0x7f0b0084
            static member Widget_MediaRouter_Light_MediaRouteButton = 2131427460
            
            // aapt resource value: 0x7f0b0083
            static member Widget_MediaRouter_MediaRouteButton = 2131427459
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Styleable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private ActionBar:int[]
            
            // aapt resource value: 10
            static member ActionBar_background = 10
            
            // aapt resource value: 12
            static member ActionBar_backgroundSplit = 12
            
            // aapt resource value: 11
            static member ActionBar_backgroundStacked = 11
            
            // aapt resource value: 13
            static member ActionBar_customNavigationLayout = 13
            
            // aapt resource value: 3
            static member ActionBar_displayOptions = 3
            
            // aapt resource value: 9
            static member ActionBar_divider = 9
            
            // aapt resource value: 1
            static member ActionBar_height = 1
            
            // aapt resource value: 14
            static member ActionBar_homeLayout = 14
            
            // aapt resource value: 7
            static member ActionBar_icon = 7
            
            // aapt resource value: 16
            static member ActionBar_indeterminateProgressStyle = 16
            
            // aapt resource value: 18
            static member ActionBar_itemPadding = 18
            
            // aapt resource value: 8
            static member ActionBar_logo = 8
            
            // aapt resource value: 2
            static member ActionBar_navigationMode = 2
            
            // aapt resource value: 17
            static member ActionBar_progressBarPadding = 17
            
            // aapt resource value: 15
            static member ActionBar_progressBarStyle = 15
            
            // aapt resource value: 4
            static member ActionBar_subtitle = 4
            
            // aapt resource value: 6
            static member ActionBar_subtitleTextStyle = 6
            
            // aapt resource value: 0
            static member ActionBar_title = 0
            
            // aapt resource value: 5
            static member ActionBar_titleTextStyle = 5
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private ActionBarLayout:int[]
            
            // aapt resource value: 0
            static member ActionBarLayout_android_layout_gravity = 0
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private ActionBarWindow:int[]
            
            // aapt resource value: 0
            static member ActionBarWindow_windowActionBar = 0
            
            // aapt resource value: 1
            static member ActionBarWindow_windowActionBarOverlay = 1
            
            // aapt resource value: 2
            static member ActionBarWindow_windowSplitActionBar = 2
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private ActionMenuItemView:int[]
            
            // aapt resource value: 0
            static member ActionMenuItemView_android_minWidth = 0
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private ActionMenuView:int[]
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private ActionMode:int[]
            
            // aapt resource value: 3
            static member ActionMode_background = 3
            
            // aapt resource value: 4
            static member ActionMode_backgroundSplit = 4
            
            // aapt resource value: 0
            static member ActionMode_height = 0
            
            // aapt resource value: 2
            static member ActionMode_subtitleTextStyle = 2
            
            // aapt resource value: 1
            static member ActionMode_titleTextStyle = 1
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private ActivityChooserView:int[]
            
            // aapt resource value: 1
            static member ActivityChooserView_expandActivityOverflowButtonDrawable = 1
            
            // aapt resource value: 0
            static member ActivityChooserView_initialActivityCount = 0
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private AdsAttrs:int[]
            
            // aapt resource value: 0
            static member AdsAttrs_adSize = 0
            
            // aapt resource value: 1
            static member AdsAttrs_adSizes = 1
            
            // aapt resource value: 2
            static member AdsAttrs_adUnitId = 2
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private CompatTextView:int[]
            
            // aapt resource value: 0
            static member CompatTextView_textAllCaps = 0
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private LinearLayoutICS:int[]
            
            // aapt resource value: 0
            static member LinearLayoutICS_divider = 0
            
            // aapt resource value: 2
            static member LinearLayoutICS_dividerPadding = 2
            
            // aapt resource value: 1
            static member LinearLayoutICS_showDividers = 1
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private MapAttrs:int[]
            
            // aapt resource value: 1
            static member MapAttrs_cameraBearing = 1
            
            // aapt resource value: 2
            static member MapAttrs_cameraTargetLat = 2
            
            // aapt resource value: 3
            static member MapAttrs_cameraTargetLng = 3
            
            // aapt resource value: 4
            static member MapAttrs_cameraTilt = 4
            
            // aapt resource value: 5
            static member MapAttrs_cameraZoom = 5
            
            // aapt resource value: 0
            static member MapAttrs_mapType = 0
            
            // aapt resource value: 6
            static member MapAttrs_uiCompass = 6
            
            // aapt resource value: 7
            static member MapAttrs_uiRotateGestures = 7
            
            // aapt resource value: 8
            static member MapAttrs_uiScrollGestures = 8
            
            // aapt resource value: 9
            static member MapAttrs_uiTiltGestures = 9
            
            // aapt resource value: 10
            static member MapAttrs_uiZoomControls = 10
            
            // aapt resource value: 11
            static member MapAttrs_uiZoomGestures = 11
            
            // aapt resource value: 12
            static member MapAttrs_useViewLifecycle = 12
            
            // aapt resource value: 13
            static member MapAttrs_zOrderOnTop = 13
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private MediaRouteButton:int[]
            
            // aapt resource value: 1
            static member MediaRouteButton_android_minHeight = 1
            
            // aapt resource value: 0
            static member MediaRouteButton_android_minWidth = 0
            
            // aapt resource value: 2
            static member MediaRouteButton_externalRouteEnabledDrawable = 2
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private MenuGroup:int[]
            
            // aapt resource value: 5
            static member MenuGroup_android_checkableBehavior = 5
            
            // aapt resource value: 0
            static member MenuGroup_android_enabled = 0
            
            // aapt resource value: 1
            static member MenuGroup_android_id = 1
            
            // aapt resource value: 3
            static member MenuGroup_android_menuCategory = 3
            
            // aapt resource value: 4
            static member MenuGroup_android_orderInCategory = 4
            
            // aapt resource value: 2
            static member MenuGroup_android_visible = 2
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private MenuItem:int[]
            
            // aapt resource value: 14
            static member MenuItem_actionLayout = 14
            
            // aapt resource value: 16
            static member MenuItem_actionProviderClass = 16
            
            // aapt resource value: 15
            static member MenuItem_actionViewClass = 15
            
            // aapt resource value: 9
            static member MenuItem_android_alphabeticShortcut = 9
            
            // aapt resource value: 11
            static member MenuItem_android_checkable = 11
            
            // aapt resource value: 3
            static member MenuItem_android_checked = 3
            
            // aapt resource value: 1
            static member MenuItem_android_enabled = 1
            
            // aapt resource value: 0
            static member MenuItem_android_icon = 0
            
            // aapt resource value: 2
            static member MenuItem_android_id = 2
            
            // aapt resource value: 5
            static member MenuItem_android_menuCategory = 5
            
            // aapt resource value: 10
            static member MenuItem_android_numericShortcut = 10
            
            // aapt resource value: 12
            static member MenuItem_android_onClick = 12
            
            // aapt resource value: 6
            static member MenuItem_android_orderInCategory = 6
            
            // aapt resource value: 7
            static member MenuItem_android_title = 7
            
            // aapt resource value: 8
            static member MenuItem_android_titleCondensed = 8
            
            // aapt resource value: 4
            static member MenuItem_android_visible = 4
            
            // aapt resource value: 13
            static member MenuItem_showAsAction = 13
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private MenuView:int[]
            
            // aapt resource value: 4
            static member MenuView_android_headerBackground = 4
            
            // aapt resource value: 2
            static member MenuView_android_horizontalDivider = 2
            
            // aapt resource value: 5
            static member MenuView_android_itemBackground = 5
            
            // aapt resource value: 6
            static member MenuView_android_itemIconDisabledAlpha = 6
            
            // aapt resource value: 1
            static member MenuView_android_itemTextAppearance = 1
            
            // aapt resource value: 7
            static member MenuView_android_preserveIconSpacing = 7
            
            // aapt resource value: 3
            static member MenuView_android_verticalDivider = 3
            
            // aapt resource value: 0
            static member MenuView_android_windowAnimationStyle = 0
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private SearchView:int[]
            
            // aapt resource value: 2
            static member SearchView_android_imeOptions = 2
            
            // aapt resource value: 1
            static member SearchView_android_inputType = 1
            
            // aapt resource value: 0
            static member SearchView_android_maxWidth = 0
            
            // aapt resource value: 3
            static member SearchView_iconifiedByDefault = 3
            
            // aapt resource value: 4
            static member SearchView_queryHint = 4
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private Spinner:int[]
            
            // aapt resource value: 4
            static member Spinner_android_dropDownHorizontalOffset = 4
            
            // aapt resource value: 1
            static member Spinner_android_dropDownSelector = 1
            
            // aapt resource value: 5
            static member Spinner_android_dropDownVerticalOffset = 5
            
            // aapt resource value: 3
            static member Spinner_android_dropDownWidth = 3
            
            // aapt resource value: 0
            static member Spinner_android_gravity = 0
            
            // aapt resource value: 2
            static member Spinner_android_popupBackground = 2
            
            // aapt resource value: 9
            static member Spinner_disableChildrenWhenDisabled = 9
            
            // aapt resource value: 8
            static member Spinner_popupPromptView = 8
            
            // aapt resource value: 6
            static member Spinner_prompt = 6
            
            // aapt resource value: 7
            static member Spinner_spinnerMode = 7
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private Theme:int[]
            
            // aapt resource value: 0
            static member Theme_actionDropDownStyle = 0
            
            // aapt resource value: 1
            static member Theme_dropdownListPreferredItemHeight = 1
            
            // aapt resource value: 5
            static member Theme_listChoiceBackgroundIndicator = 5
            
            // aapt resource value: 4
            static member Theme_panelMenuListTheme = 4
            
            // aapt resource value: 3
            static member Theme_panelMenuListWidth = 3
            
            // aapt resource value: 2
            static member Theme_popupMenuStyle = 2
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private View:int[]
            
            // aapt resource value: 0
            static member View_android_focusable = 0
            
            // aapt resource value: 2
            static member View_paddingEnd = 2
            
            // aapt resource value: 1
            static member View_paddingStart = 1
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

